# Generated by Django 2.1.2 on 2020-06-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200604_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityperiod',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityperiods', to='myapi.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='activityperiod',
            unique_together={('user', 'id')},
        ),
    ]
