# Generated by Django 2.1.2 on 2020-06-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200604_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
